version: '3.4'

services:
  alstraverse-audit:
    build:
      context: ./db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
