version: '3.4'

services:
  alstraverse-audit:
    build:
      context: .
    ports:
      - 27017:27017
    environment:
      - AUDITOR_ROOT_USERNAME=root
      - AUDITOR_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
